### ISSUE TITLE
Monospace Font on the Homepage

### ISSUE THREAD

**Issue by sam-the-programmer** [aimhubio/aimstack.io#50]
In code blocks, the monospace font is not appearing in the text blocks.

![image](https://github.com/aimhubio/aimstack.io/assets/85027459/d38a64c4-18e6-432e-8093-f2ac1b274bcf)

**Comment by sam-the-programmer** [comment]
I'm assuming it's not intentional.

**Comment by arsengit** [comment]
Hi @sam-the-programmer, thank you for raising this issue. The fixing PR has already been merged.
